config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#index'

  namespace :api do
    namespace :v1 do
      resources :shoes, only: [:index]
    end
  end

  resources :shoes do
    resources :reviews, only: [:new, :edit, :update, :create, :destroy] do
    end
  end

  resources :users, only: [:index, :destroy]

  namespace :api do
    namespace :v1 do
      resources :shoes, only: [:index]
      resources :reviews, only: [:index] do
        resources :votes, only: [:index, :create]
      end
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :shoe
  has_many :votes
  has_many :users, through: :votes
  belongs_to :user

  validates :rating, presence: true, numericality: { only_integer: true}, inclusion: { in: 1..5, message: "must be between 1 - 5"}
  validates :shoe, presence: true

end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :user

  has_many :reviews, dependent: :destroy

  validates :model, presence: true
  validates :version, presence: true
  validates :brand, presence: true
  validates :picture, presence: true
  validates :picture, format: { with: URI::regexp(%w(http https)) }
  validates :year, presence: true, length: { is: 4 }, numericality: { only_integer: true }
  validates :price, presence: true
  validates :price, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: {greater_than: 0}
  validates :description, presence: true
  validates :user, presence: true

  def self.search(search)
  where("brand ILIKE ? OR model ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :photo, PhotoUploader
  has_many :shoes
  has_many :votes
  has_many :reviews, through: :votes
  has_many :reviews

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true
  validates :username, length: { maximum: 15 }
  validates :username, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/vote.rb
class Vote < ApplicationRecord

  belongs_to :review
  belongs_to :user

end

app/controllers/api/v1/shoes_controller.rb
class Api::V1::ShoesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @shoes = Shoe.all
    render json: @shoes
  end
end

app/controllers/api/v1/votes_controller.rb
class Api::V1::VotesController < ApplicationController
  respond_to :json

  def index
    @review = Review.find(params["review_id"].to_i)
    render json: @review.tally
  end

  def create
    @poll = JSON.parse(request.body.read)["poll"]
    @review = Review.find(params["review_id"].to_i)
    @user = current_user
    voted = Vote.where({user_id: @user, review_id: @review.id})
    if voted.exists?
      @review = vote_exists(voted, @poll, @review)
    else
      @review = new_vote(@user, @poll, @review)
    end
    @review.save
    render json: @review.tally
  end

  private

  def vote_exists(voted, poll, review)
    vote = voted.first
    if vote.poll == poll
      review = delete_vote(vote, poll, review)
    else
      review = change_vote(vote, poll, review)
    end
    return review
  end

  def delete_vote(vote, poll, review)
    vote.destroy
    if poll
      review.tally -= 1
    else
      review.tally += 1
    end
    return review
  end

  def change_vote(vote, poll, review)
    vote.poll = poll
    vote.save
    if poll
      review.tally += 2
    else
      review.tally -= 2
    end
    return review
  end

  def new_vote(user, poll, review)
    vote = Vote.new(review: review, user: user, poll: poll)
    vote.save
    if poll
      review.tally += 1
    else
      review.tally -= 1
    end
    return review
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  protect_from_forgery unless: -> { request.format.json? }

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:index]

  protected

  def configure_permitted_parameters
    update_attrs = [:password, :password_confirmation, :current_password, :email]
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # def index
  #   @shoe = Shoe.find(params[:shoe_id])
  #   @reviews = @shoe.reviews
  # end

  def new
    @shoe = Shoe.find(params[:shoe_id])
    @review = Review.new
  end

  def create
    @shoe = Shoe.find(params[:shoe_id])
    @review = Review.new(review_params)
    @review.shoe = @shoe
    @review.user = current_user
    if @review.save
      ReviewMailer.new_review(@review).deliver_now
      flash[:notice] =  "Review added successfully"
      redirect_to shoe_path(@shoe)
    else
      flash[:notice] = @review.errors.full_messages
      redirect_to shoe_path(@shoe)
    end
  end

  def edit
    @shoe = Shoe.find(params[:shoe_id])
    @review = Review.find(params[:id])
    if @review.user != current_user
      flash[:notice] =  "Only review owner can update review information"
      redirect_to shoe_path(@shoe)
    end
  end

  def update
    @shoe = Shoe.find(params[:shoe_id])
    @review = Review.find(params[:id])
    if @review.user == current_user && @review.update(review_params)
      flash[:notice] =  "Review updated successfully"
      redirect_to shoe_path(@shoe)
    else
      flash.now[:notice] = @review.errors.full_messages
      render :edit
    end
  end

  def destroy
    @shoe = Shoe.find(params[:shoe_id])
    @review = Review.find(params[:id])
    if @review.user == current_user || current_user.admin?
      @review.votes.each do |vote|
        vote.destroy
      end
      @review.destroy
      redirect_to @shoe
    else
      flash[:notice] =  "Only review owner can delete review"
      redirect_to @shoe
    end
  end

  private

  def review_params
    params.require(:review).permit(:description, :rating, :tally)
  end

end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController

  def index
    @shoes = Shoe.all
    if params[:search]
      @shoes = Shoe.search(params[:search]).order("created_at DESC")
    else
      @shoes = Shoe.all.order("created_at DESC")
    end
  end

  def show
    @shoe = Shoe.find(params[:id])
    @review = Review.new
    @reviews = @shoe.reviews
    @reviews = @reviews.order("tally DESC")
  end

  def new
    @shoe = Shoe.new
  end

  def create
    @shoe = Shoe.new(shoe_params)
    @shoe.user = current_user
    if @shoe.save
      flash[:notice] =  "Shoe added successfully"
      redirect_to shoe_path(@shoe)
    else
      flash.now[:notice] = @shoe.errors.full_messages
      render :new
    end
  end

  def edit
    @shoe = Shoe.find(params[:id])
    if @shoe.user != current_user
      flash[:notice] =  "Only shoe owner can update shoe information"
      redirect_to shoe_path(@shoe)
    end
  end

  def update
    @shoe = Shoe.find(params[:id])
    if @shoe.user == current_user && @shoe.update(shoe_params)
      flash[:notice] =  "Shoe updated successfully"
      redirect_to shoe_path(@shoe)
    else
      flash.now[:notice] = @shoe.errors.full_messages
      render :edit
    end
  end

  def destroy
    @shoe = Shoe.find(params[:id])
    if @shoe.user == current_user || current_user.admin?
      @shoe.destroy
      redirect_to shoes_path
    else
      flash[:notice] =  "Only shoe owner or Admin can delete shoe"
      redirect_to shoe_path(@shoe)
    end
  end

  private

  def shoe_params
    params.require(:shoe).permit(:brand, :model, :version, :picture, :year, :price, :description)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if current_user.admin?
      @users = User.all
    else
      flash[:notice] =  "Only Admin can see this page"
      redirect_to shoes_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user.admin?
      @user.shoes.destroy_all
      @user.reviews.destroy_all
      @user.destroy
      redirect_to users_path
    else
      flash[:notice] =  "Only Admin can delete users"
      redirect_to shoes_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoleMate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <nav>
      <div class="row">
        <div class="top-bar-left">
        <% if user_signed_in? %>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
        </div>
        <div class="top-bar-right">
           <%= link_to 'Change My User Info', edit_user_registration_path %>
          <%= image_tag(current_user.photo_url) if current_user.photo_url %>
        </div>
        <% if current_user.admin? %>
          <div class="list-of-users">
            <%= link_to 'List of Users', users_path %>
          </div>
        <% end %>
      </div>
        <%else%>
        <div class="row">
          <div class="top-bar-left">
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          </div>
          <div class="top-bar-right">
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </div>
      </div>
    </nav>

    <% if notice.is_a?(Array) %>
      <% notice.each do |this_notice| %>
        <p class="notice"><%= this_notice %></p>
      <% end %>
    <%elsif notice %>
      <p class="notice"> <%= notice %></p>
    <% end %>

    <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/reviews/edit.html.erb
<h1>Update Review Form</h1>

<div class-"row">
  <%= form_for [@shoe, @review] do |f| %>
  <div class="large-2 columns">
    <%= f.label :rating, :class => "review_heading" %>
    <%= f.select :rating, [[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]] %>
  </div>
  <div class="large-10 columns">
    <%= f.label :description, "Review", :class => "review_heading" %>
    <%= f.text_field :description %>
  </div>
    <div class="links">
      <%= f.submit "Update Review", :class => "update_review" %>
    <% end %>
  </div>
</div>

app/views/shoes/edit.html.erb
<h1 class= "text-center">Update Shoe Form</h1>
<div class = "row">
<%= form_for(@shoe) do |f| %>
<div class="large-6 columns">
  <div class="field">
    <%= f.label :brand, 'Brand' %><br/>
    <%= f.text_field :brand %>
  </div>

 <div class="field">
    <%= f.label :model %><br/>
    <%= f.text_field :model %>
  </div>

 <div class="field">
    <%= f.label :version %><br/>
    <%= f.text_field :version %>
  </div>
</div>
  <div class="large-6 columns">
 <div class="field">
    <%= f.label :picture %><br/>
    <%= f.text_field :picture %>
  </div>

 <div class="field">
    <%= f.label :year %><br/>
    <%= f.text_field :year %>
  </div>

 <div class="field">
    <%= f.label :price %><br/>
    <%= f.text_field :price %>
  </div>
</div>
<div class="large-12 columns">
 <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </div>
</div>
<div class="links">
  <div class="actions">
    <%= f.submit "Update Shoe", :class => "update_review"%>
  </div>
<% end %>

<p><%= link_to "Back To Shoe", @shoe %></p>
</div>

app/views/shoes/index.html.erb
<h2 class="text-center"><%=link_to "<button>Add New Shoe</button>".html_safe, new_shoe_path %></h2>
<ul>
<% @shoes.each do |shoe| %>
 <div class="row">
    <div class="large-6 columns">
      <li><%= link_to "#{shoe.brand} #{shoe.model} #{shoe.version}", shoe %> </li>
      <%= image_tag(shoe.picture) %>
    </div>
  <% end %>
</div>

<div class="links">
  <p><%= link_to "Back To Shoes", root_path %></p>
</div>

app/views/shoes/new.html.erb
<h1 class= "text-center">New Shoe Form</h1>
  <div class = "row">
  <%= form_for(@shoe) do |f| %>
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :brand, 'Brand' %><br/>
      <%= f.text_field :brand %>
    </div>

   <div class="field">
      <%= f.label :model %><br/>
      <%= f.text_field :model %>
    </div>

   <div class="field">
      <%= f.label :version %><br/>
      <%= f.text_field :version %>
    </div>
  </div>
    <div class="large-6 columns">
   <div class="field">
      <%= f.label :picture %><br/>
      <%= f.text_field :picture, placeholder: "Please enter a complete image web address"%>
    </div>

   <div class="field">
      <%= f.label :year %><br/>
      <%= f.text_field :year %>
    </div>

   <div class="field">
      <%= f.label :price %><br/>
      <%= f.text_field :price %>
    </div>
  </div>
 <div class="large-12 columns">
   <div class="field">
      <%= f.label :description %><br/>
      <%= f.text_area :description %>
    </div>
  </div>
  <div class="links">
   <div class="actions">
      <%= f.submit "Add Shoe"%>
   </div>
<% end %>
<p><%= link_to "Back To Shoes", root_path %></p>

</div>

app/views/shoes/show.html.erb
<h1> <%= @shoe.brand %> <%= @shoe.model %> <%= @shoe.version %> </h1>
<div class="row">
  <div class="large-6 columns">
    <div class="pic">
      <%= image_tag(@shoe.picture) %>
    </div>
  </div>
  <div class="large-6 columns">
    <p> Made in: <%= @shoe.year%> </p>
    <p> Price: $<%= @shoe.price %> </p>
    <p> Description: <%= @shoe.description %> </p>
  </div>
</div>
<div class="row">
  <%= form_for [@shoe, @review] do |f| %>
  <div class="large-2 columns">
    <%= f.label :rating, :class => "review_heading" %>
    <%= f.select :rating, [[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]] %>
  </div>
    <div class="large-10 columns">
    <%= f.label :description, "Review", :class => "review_heading" %>
    <%= f.text_field :description %>
    </div>
    <div class="links center">
      <%= f.submit "Add Review", :class => "update_review"%>
    </div>
    <% end %>
  </div>
</div>


<ul>
  <% @reviews.each do |review| %>

  <li>
    <div class="row review">
      <div class="large-1 columns box1">
        <div class="vote" data-id="<%= review.id %>"></div>
      </div>
      <div class="large-9 columns box3 end">
        <p id="rating"> Rating: <%= review.rating %> </p>
        <p> <%= review.description %> </p>
      </div>
      <div class="large-2 columns box4">
        <% if review.user == current_user %>
          <%= link_to "Update Review", edit_shoe_review_path(@shoe, review), params:{review: review.id}%></br>
        <% end %>
        <% if review.user == current_user || current_user.admin? %>
          <%= link_to "Delete", shoe_review_path(@shoe, review), method: :delete, params:{review: review.id}, data: {confirm: "Are you sure?"} %>
        <% end %>
        </div>
      </li>
      <% end %>
    </div>
  </div>
</ul>

<div class="row">
  <% if @shoe.user == current_user %>
    <div class="links">
      <p id="links_color"><%= link_to "Update Shoe Information", edit_shoe_path %></p>
    </div>
  <% end %>

  <% if @shoe.user == current_user || current_user.admin? %>
    <div class="links">
      <p><%= link_to "Delete Shoe", @shoe, method: :delete %></p>
    </div>
  <% end %>
  <div class="links">
    <p><%= link_to "Back To Shoes", root_path %></p>
  </div>
</div>

app/views/static_pages/index.html.erb
<div id="search-div">
<%= form_tag(shoes_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Find Your SoleMate" %>
  <%= submit_tag "Search", :name => nil, id: "search-bar" %>
<% end %>
</div>

<div id="app"></div>

app/views/users/index.html.erb
<h3>SoleMate Users </h3>

<% @users.each do |user| %>
  <div>
    <% if user.id != current_user.id %>
      <p><%= user.username %> <%= link_to "Delete User", user, method: :delete %></p>
    <% end %>
  </div>
<% end %>

<div class="links">
  <p><%= link_to "Back To Shoes", root_path %></p>
</div>